version: '3.1'

services:
  appdb:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: HotSprocket123!
      MSSQL_PID: Developer
    ports:
      - 1401:1433
    user: 0:0 # run as root inside container
    volumes:
      - mssql-volume:/var/opt/mssql

volumes:
  mssql-volume:
    external: true
